---
title: "Análise USArrests"
author: "Luciana Luz"
date: "11/13/2022"
output: html_document
---


```{r setup, include=FALSE}
# carregar as bibliotecas
pacman::p_load(cluster, ggplot2, plotly)

# pré-processamento
USArrests_cluster <- USArrests
str(USArrests_cluster)

# setar semente aleatória
set.seed(1)

# Agrupamento com kmeans

# aprendizagem ns
cls <- kmeans(x = USArrests_cluster, centers = 3) 

# passando os clusters para a base original
USArrests_cluster$cluster <- as.factor(cls$cluster)
head(USArrests_cluster)
```

# Agrupamento dos dados 'USArrests'
## K-means

Abaixo, segue o agrupamento da base de dados USArrests, usando a técnica de k-means.

```{r iriscluster, echo=FALSE, warning=FALSE, message=FALSE}
grafico1 <- ggplot() +
  geom_point(data = USArrests_cluster, mapping = aes(x = Assault, y = UrbanPop, colour = cluster)) + 
  geom_point(mapping = aes_string(x = cls$centers[ , "Assault"], y = cls$centers[ , "UrbanPop"]), color = "red", size = 4) +
  geom_text(mapping = aes_string(x = cls$centers[ , "Assault"], y = cls$centers[ , "UrbanPop"], label = 1:3), color = "white", size = 2) +
  theme_light()
ggplotly(grafico1)
```





```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
